[formatting]
align_entries     = true
array_auto_expand = false
indent_string     = "    "
reorder_keys      = true

[[rule]]
exclude = ["**/Makefile.toml"]
include = ["**/*.toml"]

[rule.formatting]
reorder_arrays = true

[[rule]]
exclude = ["**/Cargo.toml"]
include = ["**/*.toml"]

[rule.formatting]
array_auto_expand = true
