[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "target-feature=+simd128,+bulk-memory,+nontrapping-fptoint,+sign-ext",
]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
