/* File generated by the BNF Converter (bnfc 2.9.6). */

/*** Visitor Traversal Skeleton. ***/
/* This traverses the abstract syntax tree.
   To use, copy Skeleton.h and Skeleton.c to
   new files. */

#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>

#include "Skeleton.h"

void visitGraph(Graph p, Visitor *visitor, void *context) {
  visitor->visitGraphCallback(p, context);

  switch (p->kind) {
  case is_GTensor:
    visitor->visitIsGTensorCallback(p, context);
    visitGraph(p->u.gTensor_.graph_1, visitor, context);
    visitGraph(p->u.gTensor_.graph_2, visitor, context);
    break;
  case is_GNominate:
    visitor->visitIsGNominate(p, context);
    visitBinding(p->u.gNominate_.binding_, visitor, context);
    break;
  case is_GEdgeAnon:
    visitor->visitIsGEdgeAnon(p, context);
    visitBinding(p->u.gEdgeAnon_.binding_1, visitor, context);
    visitBinding(p->u.gEdgeAnon_.binding_2, visitor, context);
    break;
  case is_GEdgeNamed:
    visitor->visitIsGEdgeNamed(p, context);
    visitName(p->u.gEdgeNamed_.name_, visitor, context);
    visitBinding(p->u.gEdgeNamed_.binding_1, visitor, context);
    visitBinding(p->u.gEdgeNamed_.binding_2, visitor, context);
    break;
  case is_GRuleAnon:
    visitor->visitIsGRuleAnonCallback(p, context);
    visitGraph(p->u.gRuleAnon_.graph_1, visitor, context);
    visitGraph(p->u.gRuleAnon_.graph_2, visitor, context);
    break;
  case is_GRuleNamed:
    visitor->visitIsGRuleNamedCallback(p, context);
    visitName(p->u.gRuleNamed_.name_, visitor, context);
    visitGraph(p->u.gRuleNamed_.graph_1, visitor, context);
    visitGraph(p->u.gRuleNamed_.graph_2, visitor, context);
    break;
  case is_GSubgraph:
    visitor->visitIsGSubgraphCallback(p, context);
    visitGraphBinding(p->u.gSubgraph_.graphbinding_, visitor, context);
    break;
  case is_GVertex:
    visitor->visitIsGVertexCallback(p, context);
    visitVertex(p->u.gVertex_.vertex_, visitor, context);
    visitGraph(p->u.gVertex_.graph_, visitor, context);
    break;
  case is_GVar:
    visitor->visitIsGVarCallback(p, context);
    visitLVar(p->u.gVar_.lvar_, visitor, context);
    visitGraph(p->u.gVar_.graph_, visitor, context);
    break;
  case is_GNil:
    visitor->visitIsGNilCallback(p, context);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Graph!\n");
    exit(1);
  }
}

void visitBinding(Binding p, Visitor *visitor, void *context) {

  visitor->visitBindingCallback(p, context);

  switch (p->kind) {
  case is_VBind:
    visitor->visitIsVBindCallback(p, context);
    visitLVar(p->u.vBind_.lvar_, visitor, context);
    visitVertex(p->u.vBind_.vertex_, visitor, context);
    visitGraph(p->u.vBind_.graph_, visitor, context);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Binding!\n");
    exit(1);
  }
}

void visitGraphBinding(GraphBinding p, Visitor *visitor, void *context) {
  switch (p->kind) {
  case is_GBind:
    visitor->visitIsGBindCallback(p, context);
    visitUVar(p->u.gBind_.uvar_, visitor, context);
    visitGraph(p->u.gBind_.graph_1, visitor, context);
    visitGraph(p->u.gBind_.graph_2, visitor, context);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing GraphBinding!\n");
    exit(1);
  }
}

void visitAttrVal(AttrVal p, Visitor *visitor, void *context)
{
  visitor->visitAttrVal(p);

  switch(p->kind)
  {
  case is_AttributeValue:
    visitor->visitIsAttributeValue(p->u.attributeValue_.lvar_, context);
    visitLVar(p->u.attributeValue_.lvar_);
    break;
  case is_AttributeValueQuoted:
    visitor->visitIsAttributeValueQuoted(p->u.attributeValueQuoted_.lvar_, context)
    visitLVar(p->u.attributeValueQuoted_.lvar_);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing AttrVal!\n");
    exit(1);
  }
}

void visitAttrName(AttrName p, Visitor *visitor, void *context)
{
  visitor->visitAttrName(p);

  switch(p->kind)
  {
  case is_AttributeName:
    visitor->visitIsAttributeName(p->u.attributeName_.lvar_, context);
    visitLVar(p->u.attributeName_.lvar_, visitor, context);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing AttrName!\n");
    exit(1);
  }
}

void visitAttr(Attr p, Visitor *visitor, void *context)
{
  visitor->visitAttr(p, context);

  switch(p->kind)
  {
  case is_AttributePair:
    visitor->visitIsAttributePair(p->u.attributePair_.attrname_, context);
    visitAttrName(p->u.attributePair_.attrname_, visitor, context);
    visitAttrVal(p->u.attributePair_.attrval_, visitor, context);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Attr!\n");
    exit(1);
  }
}

void visitListAttr(ListAttr p, Visitor *visitor, void *context)
{
  visitor->visitListAttr(p, context);

  switch(p->kind)
  {
  case is_EmptyAttrList:
    visitor->visitIsEmptyAttrList(p, visitor, context);
    break;
  case is_AttrList:
    visitor->visitIsAttrList(p->u.attrList_.attr_, context);
    visitAttr(p->u.attrList_.attr_,visitor, context);
    visitListAttr(p->u.attrList_.listattr_,visitor, context);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing ListAttr!\n");
    exit(1);
  }
}

void visitVertex(Vertex p, Visitor *visitor, void *context) {

  visitor->visitVertexCallback(p, context);

  switch (p->kind) {
  case is_VName:
    visitor->visitIsVNameCallback(p, context);
    visitName(p->u.vName_.name_, visitor, context);
    visitListAttr(p->u.vName_.listattr_, visitor, context);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Vertex!\n");
    exit(1);
  }
}

void visitName(Name p, Visitor *visitor, void *context) {
  switch (p->kind) {
  case is_NameWildcard:
    visitor->visitIsNameWildcardCallback(p, context);
    break;
  case is_NameVVar:
    visitor->visitIsNameVVarCallback(p, context);
    break;
  case is_NameGVar:
    visitor->visitIsNameGVarCallback(p, context);
    break;
  case is_NameQuoteGraph:
    visitor->visitIsNameQuoteGraph(p, context);
    visitGraph(p->u.nameQuoteGraph_.graph_, visitor, context);
    break;
  case is_NameQuoteVertex:
    visitor->visitIsNameQuoteVertex(p, context);
    visitVertex(p->u.nameQuoteVertex_.vertex_, visitor, context);
    break;

  default:
    fprintf(stderr, "Error: bad kind field when printing Name!\n");
    exit(1);
  }
}

void visitListName(ListName listname, Visitor *visitor, void *context) {
  visitor->visitListName(listname, context);

  while (listname != 0) {
    visitName(listname->name_, visitor, context);
    listname = listname->listname_;
  }
}

void visitUVar(UVar p, Visitor *visitor, void *context) {
  visitor->visitUVar(p, context);
}
void visitLVar(LVar p, Visitor *visitor, void *context) {
  visitor->visitLVar(p, context);
}
void visitIdent(Ident i, Visitor *visitor, void *context) {
  visitor->visitIdent(i, context);
}
void visitInteger(Integer i, Visitor *visitor, void *context) {
  visitor->visitIntegerCallback(i, context);
}
void visitDouble(Double d, Visitor *visitor, void *context) {
  visitor->visitDoubleCallback(d, context);
}
void visitChar(Char c, Visitor *visitor, void *context) {
  visitor->visitCharCallback(c, context);
}
void visitString(String s, Visitor *visitor, void *context) {
  visitor->visitStringCallback(s, context);
}
